# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geo_coder"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Dempsey"]
  s.date = "2011-09-21"
  s.description = "Geocode a text address."
  s.email = "dempsey.travis@gmail.com"
  s.executables = ["build_indexes", "rebuild_cluster", "rebuild_metaphones", "tiger_import"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "Makefile",
    "Manifest.txt",
    "README.rdoc",
    "TODO.txt",
    "VERSION",
    "bin/build_indexes",
    "bin/rebuild_cluster",
    "bin/rebuild_metaphones",
    "bin/tiger_import",
    "demos/demo/app/ext/geocodewrap.rb",
    "demos/demo/app/views/index.builder",
    "demos/demo/app/views/index.erb",
    "demos/demo/config.ru",
    "demos/demo/config/bootstraps.rb",
    "demos/demo/config/geoenvironment.rb",
    "demos/demo/geocoder_helper.rb",
    "demos/demo/geocom_geocode.rb",
    "demos/demo/main.rb",
    "demos/demo/rakefile.rb",
    "demos/demo/tmp/restart.txt",
    "demos/simpledemo/views/index.builder",
    "demos/simpledemo/views/index.erb",
    "demos/simpledemo/ws.rb",
    "doc/Makefile",
    "doc/html4css1.css",
    "doc/lookup.rst",
    "doc/parsing.rst",
    "doc/voidspace.css",
    "lib/geocoder/us.rb",
    "lib/geocoder/us/address.rb",
    "lib/geocoder/us/constants.rb",
    "lib/geocoder/us/database.rb",
    "lib/geocoder/us/import.rb",
    "lib/geocoder/us/import/tiger.rb",
    "lib/geocoder/us/numbers.rb",
    "navteq/README",
    "navteq/convert.sql",
    "navteq/navteq_import",
    "navteq/prepare.sql",
    "sql/cluster.sql",
    "sql/convert.sql",
    "sql/create.sql",
    "sql/index.sql",
    "sql/place.csv",
    "sql/place.sql",
    "sql/setup.sql",
    "src/Makefile",
    "src/README",
    "src/liblwgeom/Makefile",
    "src/liblwgeom/box2d.c",
    "src/liblwgeom/lex.yy.c",
    "src/liblwgeom/liblwgeom.h",
    "src/liblwgeom/lwalgorithm.c",
    "src/liblwgeom/lwalgorithm.h",
    "src/liblwgeom/lwcircstring.c",
    "src/liblwgeom/lwcollection.c",
    "src/liblwgeom/lwcompound.c",
    "src/liblwgeom/lwcurvepoly.c",
    "src/liblwgeom/lwgeom.c",
    "src/liblwgeom/lwgeom_api.c",
    "src/liblwgeom/lwgparse.c",
    "src/liblwgeom/lwgunparse.c",
    "src/liblwgeom/lwline.c",
    "src/liblwgeom/lwmcurve.c",
    "src/liblwgeom/lwmline.c",
    "src/liblwgeom/lwmpoint.c",
    "src/liblwgeom/lwmpoly.c",
    "src/liblwgeom/lwmsurface.c",
    "src/liblwgeom/lwpoint.c",
    "src/liblwgeom/lwpoly.c",
    "src/liblwgeom/lwsegmentize.c",
    "src/liblwgeom/lwutil.c",
    "src/liblwgeom/measures.c",
    "src/liblwgeom/postgis_config.h",
    "src/liblwgeom/ptarray.c",
    "src/liblwgeom/vsprintf.c",
    "src/liblwgeom/wktparse.h",
    "src/liblwgeom/wktparse.lex",
    "src/liblwgeom/wktparse.tab.c",
    "src/liblwgeom/wktparse.tab.h",
    "src/liblwgeom/wktparse.y",
    "src/libsqlite3_geocoder/Makefile",
    "src/libsqlite3_geocoder/Makefile.nix",
    "src/libsqlite3_geocoder/Makefile.redhat",
    "src/libsqlite3_geocoder/extension.c",
    "src/libsqlite3_geocoder/extension.h",
    "src/libsqlite3_geocoder/levenshtein.c",
    "src/libsqlite3_geocoder/metaphon.c",
    "src/libsqlite3_geocoder/util.c",
    "src/libsqlite3_geocoder/wkb_compress.c",
    "src/metaphone/Makefile",
    "src/metaphone/README",
    "src/metaphone/extension.c",
    "src/metaphone/metaphon.c",
    "src/shp2sqlite/Makefile",
    "src/shp2sqlite/Makefile.nix",
    "src/shp2sqlite/Makefile.redhat",
    "src/shp2sqlite/dbfopen.c",
    "src/shp2sqlite/getopt.c",
    "src/shp2sqlite/getopt.h",
    "src/shp2sqlite/shapefil.h",
    "src/shp2sqlite/shp2sqlite.c",
    "src/shp2sqlite/shpopen.c",
    "tests/address.rb",
    "tests/benchmark.rb",
    "tests/constants.rb",
    "tests/data/address-sample.csv",
    "tests/data/db-test.csv",
    "tests/data/locations.csv",
    "tests/database.rb",
    "tests/generate.rb",
    "tests/numbers.rb",
    "tests/run.rb"
  ]
  s.homepage = "http://github.com/kornypoet/geo_coder"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Geocoder based upon the Geocommons Geocoder."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
      s.add_runtime_dependency(%q<text>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
      s.add_dependency(%q<text>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
    s.add_dependency(%q<text>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

